### ISSUE TITLE
For help.

### ISSUE THREAD

**Issue by acrazyboy** [StravopodisNikos/screw_dynamics#1]
Dear Stravopodis Nikos, thanks for sharing your code about screw_dynamics. These codes are very helpful to my study. I, a  graduate student studying at  Wuhan textile university in China, major in robotics.  Could you please tell me which  reference book you use when codeing？ Thanks again！

**Comment by acrazyboy** [comment]
> Dear Stravopodis Nikos, thanks for sharing your code about screw_dynamics. These codes are very helpful to my study. I, a graduate student studying at Wuhan textile university in China, major in robotics. Could you please tell me which reference book you use when codeing？ Thanks again！

**Comment by StravopodisNikos** [comment]
Hello my friend! My main reference book is "A Mathematical Introduction to Robotic Manipulation" by R.M. Muray, Z. Li and S.S Sastry. It is an excellent book but you should accompany it with some other book depending on your infrastructure on screw theory. At least this is what I did!

**Comment by acrazyboy** [comment]
Thank you for taking time to answer me.I really appreciate your help.Best wishes!
